### ISSUE TITLE
lang 设置无效

### ISSUE THREAD

**Issue by faydanube** [laravel-admin-extensions/ckeditor#5]
如题
@z-song

**Comment by faydanube** [comment]
@z-song  求修復……
$form->ckeditor('content', __('admin.content'))->options(['lang' => 'zh-TW', 'height' => 400]);
![image](https://user-images.githubusercontent.com/8817046/71448916-3bbfa780-277e-11ea-9f3d-0b2971f54297.png)
如圖，依然是簡體

**Comment by faydanube** [comment]
找到 lang 文件夾，設置lang=zh，依然無效，目前只能把zh的內容完全複製進zh-cn進行替換……

**Comment by vthwang** [comment]
@faydanube 
I met the same problem here.
You can change the configuration in `config/admin.php` as the following.
```
'ckeditor' => [
    'enable' => true,
    'config' => [
        'language'   => 'zh',
        'height' => 200,
    ]
]
```

**Comment by faydanube** [comment]
> @faydanube
> I met the same problem here.
> You can change the configuration in `config/admin.php` as the following.
> 
> ```
> 'ckeditor' => [
>     'enable' => true,
>     'config' => [
>         'language'   => 'zh',
>         'height' => 200,
>     ]
> ]
> ```

3q
